version: '2'
services:
  db:
    image: postgres:14
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '127.0.0.1'
    volumes:
      - .:/test_app_rails
    ports:
      - "3000:3000"
    depends_on:
      - db